### ISSUE TITLE
posix child termination: use SIGTERM instead of SIGKILL 

### ISSUE THREAD

**Issue by joergreiling** [boostorg/process#166]
Using signal 'SIGKILL' on posix for child termination shouldn't be the preferred way.

You can of course install a signal-handler for 'SIGKILL', but this handler will never be called. So the child-process has no possibilty to react on a termination (closing descriptors, flushing caches, freeing resources...), a proper shutdown is not possible. 

Why don't we use signal 'SIGTERM' instead on Linux and Mac OS? 

That's also the way how it is done by Qt/QProcess.

Feature-Request:
- use 'SIGTERM' for child::terminate()
- use 'SIGKILL' for new feature child::kill()

**Comment by klemens-morgenstern** [comment]
It is not the preferred way, it's the only way that has an equivalent on windows. 
There is no `SIGTERM` on windows that works for every process, hence there is no `terminate` in the posix sense in `boost.process` since it's a posix only feature. `TerminateProcess` is the windows version of `SIGKILL`.

**Comment by joergreiling** [comment]
Graceful process-termination on Windows: **WM_CLOSE**

**Comment by klemens-morgenstern** [comment]
Only for win32 applications, not for console application. Quite different than on posix.
