### ISSUE TITLE
Empty argument "disappears" on Windows

### ISSUE THREAD

**Issue by Capital-Z** [boostorg/process#256]
Passing empty argument to a process just adds an extra space to its command line on Windows which is normally ignored. Not sure how it would work on Posix, but makes it impossible to pass empty value under Windows.
Possible solution would be in ...process\detail\windows\basic_cmd.hpp build_args(..) which quotes arguments if necessary, to also quote empty ones. E.g. something like:
`if(!arg.empty())
{...}
else
arg = "\"\"";`

**Comment by SilverPlate3** [comment]
@Capital-Z
Can you please

post the code you tried to run.
Elaborate on the desired outcome.
I wasn't able to fully understand the issue.
Thanks!

**Comment by Capital-Z** [comment]
If I remember correctly the original problem was with a custom executable and I solved it by passing data to it in other means. But the issue is simple: how to pass empty argument?
As example ImageMagic has option -format and if you want to suppress it you pass empty string for format, i.e. from terminal: `magic.exe -format ""`
So in boost process terms it would be (not verified code just typing here):
`boost::process::child("magic.exe", boost::process::args({"-format", ""}));`
According to my original comment this would pass just "-format" to magic.exe, which is not valid input for it.
I am not sure if my original digging in boost/process code is still relevant.

**Comment by SilverPlate3** [comment]
@klemens-morgenstern 
Fixed the issue in pull request https://github.com/boostorg/process/pull/328/files
I think issue can be closed.

**Comment by fkonvick** [comment]
@klemens-morgenstern @SilverPlate3 This broke existing code for us.  We used to:
`bp::child(bp::shell, bp::args = {shell_script}, ...`
which resulted in `C:\Windows\system32\cmd.exe /c shell_script` out of `build_args` or, in case there was a space or `"` in the shell script, a quoted/escaped version: `C:\Windows\system32\cmd.exe /c "shell_script"`.  See PR #73 for fixes that were earlier introduced to fix escaping.

With this change in PR @256, we're getting
`C:\Windows\system32\cmd.exe /c "" shell_script` (note the extra empty pair of double quotes) and the script refuses to run.

I see that the co-culprit is `exe_args_shell`:  this code
```
std::vector<string_type> args_ = {c_arg(Char()), std::move(exe)};
args_.insert(args_.end(), std::make_move_iterator(args.begin()), std::make_move_iterator(args.end()));
```
adds `exe` to `args_`, but this might be empty, especially with `bp::shell`, and (newly) gets translated to the unwanted `""`.  Since this is added to args internally by BP, the end user has no visibility/clue of where this `""` is coming from.  Using `bp::exe = {shell_script}` instead of `bp::args` is a workaround that I can use now, but I still think that `exe_args_shell` should only add `exe` when it's non-empty.  Something like
```
std::vector<string_type> args_ = {c_arg(Char())};
if ( !exe.empty() )
  args_.emplace_back(std::move(exe));
args_.insert(args_.end(), std::make_move_iterator(args.begin()), std::make_move_iterator(args.end()));
```
If you agree, I can make another PR or you could just go ahead and apply this :D

**Comment by klemens-morgenstern** [comment]
A PR would be most welcome.

**Comment by fkonvick** [comment]
No problem, please see #511
