### ISSUE TITLE
static_assert within is_running.hpp is broken when building against musl

### ISSUE THREAD

**Issue by JCYang** [boostorg/process#48]
when building against musl libc. that assertion failed.
because musl contain correction for mips.
details here:
http://git.musl-libc.org/cgit/musl/commit/include/sys/wait.h?id=41c632824c08ac2c9eea43b30d1b3515dd910df6

so that assertion should be fixed.
the status code is opaque implementation detail, isn't it? that's why we need those test macro, so this is not reliable and portable at the beginning, iiuc.

**Comment by klemens-morgenstern** [comment]
Looks like it, but then I would need a new definition for the `still_running` constant - because, yes, it is an opaque detail. I didn't find a way how to do implement that otherwise, but I'd love suggestions. Otherwise, if you know what `#ifdef` to use, feel free to create a PR for a musl workaround.
