### ISSUE TITLE
calling code can't determine if normel exit or signaled

### ISSUE THREAD

**Issue by olk** [boostorg/process#61]
child::exit_code() evaluates WIFEXITED and WIFSIGNALED. Depending on that child::exit_code() returns WEXITSTATUS or WTERMSIG (see boost::process::detail::posix::eval_exit_status()).
For code calling child::exit_code() it is not possible to determine if the returned value of `9` means that the forked process returned normally with exit-code `9` or the forked process was killed by SIGKILL (9 on Linux).

**Comment by klemens-morgenstern** [comment]
A function for that is in the develop-branch, where you can call `native_exit_code` to obtain the unevaluated exit-code. I'll have that in the master for the next release cycle.

I don't think having that information included in the value returned by `exit_code()` would be the right choice, since that would be inconsistent with windows.

**Comment by olk** [comment]
OK, ty

**Comment by olk** [comment]
Unfortunately I can't find _native_exit_code_ in sources of branch develop - do I miss something?

**Comment by klemens-morgenstern** [comment]
It's [there](https://github.com/boostorg/process/blob/develop/include/boost/process/detail/child_decl.hpp#L104) - hope it works properly.

**Comment by olk** [comment]
sorry - forgot `git pull`🙄

Am Di., 8. Jan. 2019 um 11:50 Uhr schrieb Klemens Morgenstern <
notifications@github.com>:
